apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ include "helloworld-go.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helloworld-go.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helloworld-go.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helloworld-go.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
